# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: custom_theme
  theme_night: custom_theme
  font: custom_font
  font_size: M

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Xinyue, PhD student.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header
# NB: to add networking icon (e.g., twitter) => content/authors/admin/_index.md > icon: twitter > display > header: true
header:
  navbar:
    enable: true
    align: l
    show_logo: false
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer
footer:
  copyright:
    notice: '© {year} Xinyue. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: hugo
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
    engine: lunr
    placeholder: "Search..."
    max_results: 10
    show_search_results: true
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions
extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security
security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true

publications:
  date_format: "January 2006"
  citation_style: "apa"

# 配置BIB导入
import_from_bibtex:
    enable: true
    file: "content/publication/cite.bib"
    # 可选：过滤器，例如只导入类型为'article'的条目
    # filters:
    #   publication_type: "article"

params:
  custom_css: ["css/custom.css"]
params:
  publications:
    citation_style: "apa"